version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: dotnet_template_api_server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
      - USE_HTTPS=false
    ports:
      - "5000:5000"
      - "5001:5001"


volumes:
  pgdata:

